### ISSUE TITLE
听说gh极速版提交issue能刷金币，能提现吗？我的银行卡号是1145141919810,密码是7355608

### ISSUE THREAD

**Issue by aac6fef** [Molyuu/Molyuu.github.io#7]
既然社区已经做出优秀的教程了，为何要重复写？
还有，我的pr有啥问题吗.....

**Comment by Molyuu** [comment]
> 既然社区已经做出优秀的教程了，为何要重复写？
我第一次装Arch的时候看不懂“优秀的教程”

>  还有，我的pr有啥问题吗.....
No Gork,please!
另外，别发pr，提issue，谢谢！

**Comment by aac6fef** [comment]
你可以给我打钱吗？

**Comment by Molyuu** [comment]
来来来，来搞基

aac6fef ***@***.***> 于 2022年3月26日周六 21:07写道：
